spring:
  datasource:
    url: jdbc:mysql://localhost:32768/beerProjectDevelop?serverTimezone=Europe/Warsaw
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/master.xml


  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false

server:
  port: 8085

logging:
  config: classpath:logback/logback.xml