spring:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://db:3306/beerProjectDevelop?useSSL=true&serverTimezone=Europe/Warsaw
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/master.xml

  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  config: classpath:logback/logback.xml