spring:
  datasource.url: jdbc:h2:mem:testdb
  datasource:
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/test.xml

